import Head from 'next/head'
import Image from 'next/image'

export default function Home(): JSX.Element {
  const items = [
    '/img/shader-art.webp',
    '/img/sp-controller.webp',
    '/img/voice-particle.webp',
  ]

  return (
    <article>
      <Head>
        <title>Portfolio Shader</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <ul className="grid">
        {items.map((src: string) => (
          <li key={src}>
            <Image src={src} alt="" width={16 * 100} height={9 * 100} />
          </li>
        ))}
      </ul>
    </article>
  )
}
